apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.stackable.tech
spec:
  group: zookeeper.stackable.tech
  names:
    kind: ZooKeeperCluster
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  enum: [ 3.4.14 ]
                servers:
                  type: array
                  items:
                    type: object
                    properties:
                      node_name:
                        type: string                        
              required: [ "version", "servers" ]
            status:
               type: object
               properties:
                 is_bad:
                   type: boolean
      subresources:
         status: {}
