apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.stackable.tech
spec:
  group: zookeeper.stackable.tech
  names:
    kind: ZooKeeperCluster
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  enum: [ 3.4.14, 3.5.8 ]
                servers:
                  type: array
                  items:
                    type: object
                    properties:
                      node_name:
                        type: string
              required: [ "version", "servers" ]
            status:
              nullable: true
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        description: "lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
                        format: date-time
                        type: string
                      message:
                        description: message is a human readable message indicating details about the transition. This may be an empty string.
                        type: string
                      observedGeneration:
                        description: "observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance."
                        format: int64
                        type: integer
                      reason:
                        description: "reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty."
                        type: string
                      status:
                        default: Unknown
                        description: "status of the condition, one of True, False, Unknown."
                        enum:
                          - Unknown
                          - "True"
                          - "False"
                        type: string
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        pattern: "^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$"
                        type: string
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map
                currentVersion:
                  enum:
                    - 3.4.14
                    - 3.5.8
                  nullable: true
                  type: string
                targetVersion:
                  enum:
                    - 3.4.14
                    - 3.5.8
                  nullable: true
                  type: string
              type: object
      subresources:
        status: { }
