---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackable-subscription
  namespace: stackable-operators # namespace-you-want-your-operator-installed-in
spec:
  channel: preview
  name: zookeeper-operator
  source: zookeeper-operator-catalog
  sourceNamespace: stackable-operators
  installPlanApproval: Automatic # Manual
