---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 0.8.0
  clusterConfig:
    tls:
      server:
        secretClass: tls # <1>
      quorum:
        secretClass: tls # <2>
  servers:
    roleGroups:
      default:
        replicas: 3
