---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-eks
metadata:
  name: zookeper-operator-integration-tests
  description: "Cluster for Zookeeper Operator Integration Tests (AWS EKS)"
publicKeys: []
spec:
  region: "eu-central-1"
  awsInstanceType: "t2.medium"
  versions:
    _-operator: NIGHTLY
    zookeeper-operator: "$ZOOKEEPER_OPERATOR_VERSION"
  node_count: 3
