---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.3
  clusterConfig:
    tls:
      serverSecretClass: tls # <1>
      quorumSecretClass: tls # <2>
  servers:
    roleGroups:
      default:
        replicas: 3
