---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 0.0.0-dev
  clusterConfig:
    authentication:
      - authenticationClass: zk-client-tls # <1>
  servers:
    roleGroups:
      default:
        replicas: 3
