= Authentication

The quorum or server-to-server communication is authenticated via TLS per default. In order to enforce TLS authentication for client-to-server communication, you can set an `AuthenticationClass` reference in the custom resource provided by the xref:commons-operator::index.adoc[Commons Operator].

[source,yaml]
----
include::example$example-cluster-tls-authentication.yaml[]
include::example$example-cluster-tls-authentication-class.yaml[]
include::example$example-cluster-tls-authentication-secret.yaml[]
----
<1> The `clusterConfig.authentication.tls.clientAuthenticationClass` can be set to use TLS for authentication. This is optional.
<2> The referenced `AuthenticationClass` that references a `SecretClass` to provide certificates.
<3> The reference to a `SecretClass`.
<4> The `SecretClass` that is referenced by the `AuthenticationClass` in order to provide certificates.

If both `spec.clusterConfig.tls.server.secretClass` and `spec.clusterConfig.authentication.tls.clientAuthenticationClass` are set, the authentication class will take precedence over the secret class. The cluster will be encrypted and authenticate only against the authentication class.

WARNING: Due to a https://issues.apache.org/jira/browse/ZOOKEEPER-4276[bug] in ZooKeeper, the `clientPort` property in combination with `client.portUnification=true` is used instead of the `secureClientPort`. This means that unencrypted and unauthenticated access to the ZooKeeper cluster is still possible.
