== Kubernetes custom resource options
The cluster can be configured via a YAML file. This custom resource specifies the amount of replicas for each role group or role specific configuration like port definitions etc.

[source,yaml]
----
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        # Here you can set the Stackable supported configuration parameters
        # See the documentation for a full list of the exposed configuration parameters
        config:
          tickTime: 3000
        # You can also override properties in a configuration file here
        configOverrides:
          zoo.cfg:
            4lw.commands.whitelist: 'srvr,ruok,isro'
        # Set environment variables here
        envOverrides:
          MY_ENV_VAR: "foobar"
----

== Configuration Overrides
ZooKeeper uses a single file named zoo.cfg to store its runtime configuration. The configOverrides block allows you to add custom parameters to zoo.cfg. A Full list of the available configuration options can be found in the official Apache ZooKeeper documentation at https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html#sc_configuration.

Overrides consist of a key, which must match the property name in the configuration file and a value. This allows arbitrary configuration properties to be added to ZooKeeper. In the example above the property 4lw.commands.whitelist is being explicitly set to 'srvr,ruok,isro', overriding the default value.

== Configuration Properties
Below is a list of the configuration properties exposed by the Stackable ZooKeeper operator. These properties can be added to the config block of a ZooKeeper cluster CRD.

[cols="2,2,2,2,1"]
|===
| config-spec Property | Actual Property | Default Value | Recommended Value | Location

| initLimit
| initLimit
| 5
| 5
| file:zoo.cfg

| syncLimit
| syncLimit
| 2
| 2
| file:zoo.cfg

| tickTime
| tickTime
| 3000
| 3000
| file:zoo.cfg

| clientPort
| clientPort
| 2181
| 2181
| file:zoo.cfg

| dataDir
| dataDir
| /tmp/zookeeper
| /stackable/data
| file:zoo.cfg

| metricsPort
| metricsPort
|
| 57001
| env

| admin_serverPort
| admin.serverPort
| 8080
| 8080
| file:zoo.cfg

|===
