== Kubernetes custom resource options
The cluster can be configured via a YAML file. This custom resource specifies the amount of replicas for each role group or role specific configuration like port definitions etc.

[source,yaml]
----
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        # Here you can set the Stackable supported configuration parameters
        # See the documentation for a full list of the exposed configuration parameters
        config:
          tickTime: 3000
        # You can also override properties in a configuration file here
        configOverrides:
          zoo.cfg:
            4lw.commands.whitelist: 'srvr,ruok,isro'
        # Set environment variables here
        envOverrides:
          MY_ENV_VAR: "foobar"
----

== Configuration Overrides
ZooKeeper uses a single file named zoo.cfg to store its runtime configuration. The configOverrides block allows you to add custom parameters to zoo.cfg. A Full list of the available configuration options can be found in the official Apache ZooKeeper documentation at https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html#sc_configuration.

Overrides consist of a key, which must match the property name in the configuration file and a value. This allows arbitrary configuration properties to be added to ZooKeeper. In the example above the property 4lw.commands.whitelist is being explicitly set to 'srvr,ruok,isro', overriding the default value.
