= Installation

There are three ways to run the ZooKeeper Operator:

1. Helm managed Docker container deployment on Kubernetes

2. As a Docker container

3. Build from source.


== Helm
Helm allows you to download and deploy Stackable operators on Kubernetes and is by far the easiest installation method. First ensure that you have installed the Stackable Operators Helm repository:
[source,bash]
----
$ helm repo add stackable https://repo.stackable.tech/repository/helm-dev/
----
Then install the Stackable Operator for Apache ZooKeeper
[source,bash]
----
$ helm install zookeeper-operator stackable/zookeeper-operator
----

Helm will deploy the operator in a Kubernetes container and apply the CRDs for the Apache ZooKeeper service. You're now ready to deploy Apache ZooKeeper in Kubernetes.

== Docker

This Operator is published as a Docker image:

[source]
----
docker.stackable.tech/stackable/zookeeper-operator
----

When installing manually with Docker you will need to install the Stackable CRDs for Apache ZooKeeper in your Kubernetes environment. These are available on the
https://github.com/stackabletech/zookeeper-operator/tree/main/deploy/crd[Stackable GitHub repository] for this operator.
[source]
----
$ sudo kubectl apply -f zookeepercluster.crd.yaml
$ sudo kubectl apply -f start.crd.yaml
$ sudo kubectl apply -f stop.crd.yaml
$ sudo kubectl apply -f restart.crd.yaml
----

To run it straight from Docker you can use this command:
[source,bash]
----
docker run -e ZOOKEEPER_OPERATOR_LOG=trace -e KUBECONFIG=/root/.kube/k3s.yaml --mount type=bind,source="$HOME/.kube/k3s.yaml",target="/root/.kube/k3s.yaml" -it docker.stackable.tech/stackable/zookeeper-operator:latest
----

== Building the operator from source

This operator is written in Rust and is developed against the latest stable Rust release (1.56 at the time of writing).

[source]
----
cargo build
----
