= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/zookeeper-operator/crd/zookeepercluster.crd.yaml

To create a single node Apache ZooKeeper (v3.5.8) cluster with Prometheus metrics exposed on port 9505:


    cat <<EOF | kubectl apply -f -
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperCluster
    metadata:
        name: simple
    spec:
        version: 3.5.8
        servers:
            roleGroups:
                default:
                    selector:
                        matchLabels:
                            kubernetes.io/arch: stackable-linux
                    replicas: 1
                    config:
                        metricsPort: 9505
    EOF


WARNING: Due to https://github.com/stackabletech/zookeeper-operator/issues/176[#176] it is not currently possible to deploy a ZooKeeper cluster with a _selector_ that matches more nodes than the value that was specified for _replicas_.
The recommended workaround is to directly target the hosts which the ZooKeeper service should be rolled out to with a selector like the following:

----
selector:
  matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - worker-1.stackable.demo
      - worker-2.stackable.demo
      - worker-3.stackable.demo
----