= Usage

If you are not installing the operator using Helm then after installation the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/zookeeper-operator/crd/zookeepercluster.crd.yaml

To create a three-node Apache ZooKeeper (v3.5.8) cluster:


    $ cat zookeeper.yaml
    ---
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperCluster
    metadata:
      name: simple-zk
    spec:
      version: 3.5.8
      servers:
        roleGroups:
          default:
            replicas: 3
            config: {}
    $ sudo kubectl apply -f zookeeper.yaml

Afterwards, a ZookeeperZnode root can be created:

    $ cat znode.yaml
    ---
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperZnode
    metadata:
      name: simple-znode
    spec:
      clusterRef:
        name: simple-zk
        namespace: default
    $ sudo kubectl apply -f znode.yaml

Finally, a ConfigMap is created, containing a path that a ZooKeeper client can connect to:

    $ kubectl get configmap simple-znode-nodeport -o yaml
    $ $ZOOKEEPER_HOME/bin/zkCli.sh -server $(kubectl get configmap simple-znode-nodeport -o jsonpath='{.data.ZOOKEEPER}')
    
