= Usage

If you are not installing the operator using Helm then after installation the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/zookeeper-operator/crd/zookeepercluster.crd.yaml

To create a three-node Apache ZooKeeper (v3.8.0) cluster:

[source,yaml]
----
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  version: 3.8.0
  servers:
    roleGroups:
      default:
        replicas: 3
        config: {}
----

Afterwards, a xref:znodes.adoc[ZNode] can be created:

[source,yaml]
----
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-znode
spec:
  clusterRef:
    name: simple-zk
    namespace: default
----

Finally, a ConfigMap is created, containing a path that a ZooKeeper client can connect to:

    $ kubectl get configmap simple-znode-nodeport -o yaml
    $ $ZOOKEEPER_HOME/bin/zkCli.sh -server $(kubectl get configmap simple-znode-nodeport -o jsonpath='{.data.ZOOKEEPER}')

== Encryption

The quorum and client communication are encrypted by default via TLS. This requires the https://github.com/stackabletech/secret-operator[Secret Operator] to be present in order to provide certificates. The utilized certificates can be changed in a top-level config.

[source,yaml]
----
include::example$example-cluster-tls-encryption.yaml[]
----
<1> The `tls.secretClass` refers to the client-to-server encryption. Defaults to the `tls` secret.
<2> The `quorumTlsSecretClass` refers to the server-to-server quorum encryption. Defaults to the `tls` secret.

The `tls` secret is deployed from the https://github.com/stackabletech/secret-operator[Secret Operator] and looks like this:

[source,yaml]
----
include::example$example-secret-operator-tls-secret.yaml[]
----

You can create your own secrets and reference them e.g. in the `tls.secretClass` to use different certificates.

== Authentication

The quorum or server-to-server communication is authenticated via TLS per default. In order to enforce TLS authentication for client-to-server communication, you can set an `AuthenticationClass` reference in the custom resource provided by the https://github.com/stackabletech/commons-operator[Commons Operator].

[source,yaml]
----
include::example$example-cluster-tls-authentication.yaml[]
----
<1> The `config.clientAuthentication.authenticationClass` can be set to use TLS for authentication. This is optional.
<2> The referenced `AuthenticationClass` that references a `SecretClass` to provide certificates.
<3> The reference to a `SecretClass`.
<4> The `SecretClass` that is referenced by the `AuthenticationClass` in order to provide certificates.

WARNING: Due to a https://issues.apache.org/jira/browse/ZOOKEEPER-4276[bug] in ZooKeeper, the `clientPort` property in combination with `client.portUnification=true` is used instead of the `secureClientPort`. This means that unencrypted and unauthenticated access to the ZooKeeper cluster is still possible.

== Monitoring

The managed ZooKeeper instances are automatically configured to export Prometheus metrics. See
xref:home::monitoring.adoc[] for more details.

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Overriding certain properties which are set by operator (such as the ports) can interfere with the operator and can lead to problems.

=== Configuration Properties

For a role or role group, at the same level of `config`, you can specify: `configOverrides` for the `zoo.cfg`. For example, if you want to set the `4lw.commands.whitelist` to allow the `ruok` administrative command, it can be configured in the `ZookeeperCluster` resource like so:

[source,yaml]
----
servers:
  roleGroups:
    default:
      configOverrides:
        zoo.cfg:
          4lw.commands.whitelist: "srvr, ruok"
      replicas: 1
----

Just as for the `config`, it is possible to specify this at role level as well:

[source,yaml]
----
routers:
  configOverrides:
    zoo.cfg:
      4lw.commands.whitelist: "srvr, ruok"
  roleGroups:
    default:
      replicas: 1
----

All override property values must be strings.

For a full list of configuration options we refer to the Apache ZooKeeper https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html#sc_configuration[Configuration Reference].

=== Environment Variables

In a similar fashion, environment variables can be (over)written. For example per role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
      replicas: 1
----

or per role:

[source,yaml]
----
servers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      replicas: 1
----
