= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/zookeeper-operator/crd/zookeepercluster.crd.yaml

To create a single node Apache ZooKeeper (v3.5.8) cluster with Prometheus metrics exposed on port 9505:


    cat <<EOF | kubectl apply -f -
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperCluster
    metadata:
        name: simple
    spec:
        version: 3.5.8
        servers:
            roleGroups:
                default:
                    selector:
                        matchLabels:
                            kubernetes.io/arch: stackable-linux
                replicas: 1
                config:
                    metricsPort: 9505
    EOF

== Running as non-root

To start the service as a user other than `root`, add `runAsUser` to the service configuration. For example:

    # ... skipped spec contents
    config:
        metricsPort: 9505
        runAsUser: stackable

will run ZooKeeper as the user `stackable`.

The user under which the service runs must exist on the target nodes.
