= ZNodes

Apache ZooKeeper organizes all data into a hierarchical system of https://zookeeper.apache.org/doc/r3.7.0/zookeeperProgrammers.html#ch_zkDataModel[ZNodes],
which act as both files (they can have data associated with them) and folders (they can contain other znodes) when compared to a traditional (POSIX-like) file system.

In order to isolate different clients using the same ZooKeeper cluster, each client application should be assigned a unique root znode, which it can then organize
as it sees fit.

In the Stackable Operator for Apache ZooKeeper, we manage this using the `ZookeeperZnode` Kubernetes resource. The operator creates a new znode in the linked
ZooKeeper cluster, as well as xref:discovery.adoc[] that are configured to restrict access to the configured ZNode. The operator _does not_ manage the contents
of the ZNode.

CAUTION: The operator automatically deletes the znode from the ZooKeeper cluster if the Kubernetes `ZookeeperZnode` object is deleted. Recreating the
`ZookeeperZnode` object will not restore access to the data.

== Usage

The `ZookeeperZnode` object should be created by user administering the system that will use the znode. For example,
when using Apache ZooKeeper to manage an Apache Kafka cluster, the `ZookeeperZnode` object would be created by the user
creating the xref:kafka::configuration.adoc[`KafkaCluster`] object.

A basic znode can be created like so:

[source,yaml]
----
include::example$example-znode.yaml[]
----
<1> Refererence to the `ZookeeperCluster` object
<2> The namespace is implied to be the same as the namespace of the `ZookeeperZnode` if omitted

This will create corresponding xref:discovery.adoc[] referring to the specific znode, which will look roughly like this:

[source,yaml]
----
include::example$example-znode-discovery.yaml[]
----
<1> The base name of the discovery profile will be the same as the name of the `ZookeeperZnode`
<2> `{path}` will be a unique and unpredictable path that is generated by the operator
