apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-znode
spec:
  clusterRef:
    name: simple-zk
    # Optional when ZookeeperZnode is in the same Namespace as the ZookeeperCluster
    # namespace: default
