apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        # Here you can set the Stackable supported configuration parameters
        # See the documentation for a full list of the exposed configuration parameters
        config:
          adminPort: 12000
          metricsPort: 9505
          dataDir: /stackable/data
          tickTime: 3000
          clientPort: 2181
        # You can also override properties in a configuration file here
        configOverrides:
          zoo.cfg:
            4lw.commands.whitelist: 'srvr,ruok,isro'
        # Set environment variables here
        envOverrides:
          SERVER_JVMFLAGS: "-Xmx512m -javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml"
