apiVersion: zookeeper.stackable.tech/v1
kind: ZooKeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
      default2:
        selector:
          matchLabels:
            kubernetes.io/hostname: bawa-virtualbox
        instances: 1
        instancesPerNode: 1
