apiVersion: zookeeper.stackable.tech/v1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: zookeeper-1
        instances: 1
        instancesPerNode: 1
      default2:
        selector:
          matchLabels:
            kubernetes.io/hostname: zookeeper-2
        instances: 1
        instancesPerNode: 1
