apiVersion: zookeeper.stackable.tech/v1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.4.14
  servers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: main-1.stackable.demo
        instances: 1
        instancesPerNode: 1
