---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  servers:
    config:
      resources:
        storage:
          data:
            capacity: '2Gi'
        cpu:
          max: '500m'
          min: '250m'
        memory:
          limit: '1Gi'
    roleGroups:
      primary:
        replicas: 2
        config:
          myidOffset: 10
      secondary:
        replicas: 1
        config:
          myidOffset: 20
  version: 3.8.0-stackable0.7.1
  stopped: false
