
= Configuration and environment overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Overriding certain properties which are set by operator (such as the ports) can interfere with the operator and can lead to problems.

== Configuration properties

For a role or role group, at the same level of `config`, you can specify: `configOverrides` for the `zoo.cfg` and `security.properties` files.

=== Overriding entries in zoo.cfg

For example, if you want to set the `4lw.commands.whitelist` to allow the `ruok` administrative command, it can be configured in the `ZookeeperCluster` resource like so:

[source,yaml]
----
servers:
  roleGroups:
    default:
      configOverrides:
        zoo.cfg:
          4lw.commands.whitelist: "srvr, ruok"
      replicas: 1
----

Just as for the `config`, it is possible to specify this at role level as well:

[source,yaml]
----
servers:
  configOverrides:
    zoo.cfg:
      4lw.commands.whitelist: "srvr, ruok"
  roleGroups:
    default:
      replicas: 1
----

All property values must be strings.

For a full list of configuration options we refer to the Apache ZooKeeper https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html#sc_configuration[Configuration Reference].

=== Overriding entries in security.properties

The `security.properties` file is used to configure JVM security properties. It is very seldom that users need to tweak any of these, but there is one use-case that stands out and that users need to be aware of: the JVM DNS cache.

The JVM manages it's own cache of successfully resolved host names as well as a cache of host names that cannot be resolved. Some products of the Stackable stack are very sensible to the contents of these caches and their performance is heavily affected by them. Apache Zookeeper always requires up-to-date IP adreses to maintain it's quorum. To gurantee this, the JVM caches need to be effectively disabled. This can be achieved by setting the TTL of the cache entries to zero, like this:

[source,yaml]
----
servers:
  configOverrides:
    security.properties
      networkaddress.cache.ttl: '0'
      networkaddress.cache.negative.ttl: '0'
  roleGroups:
    default:
      replicas: 1
----

NOTE: The operator already disables DNS caching by default for Zookeeper, so users don't need to do it explicitely.

For details on the JVM security see https://docs.oracle.com/en/java/javase/11/security/java-security-overview1.html

== Environment variables

In a similar fashion, environment variables can be (over)written. For example per role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
      replicas: 1
----

or per role:

[source,yaml]
----
servers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      replicas: 1
----
