= Storage and resource configuration

== Storage for data volumes

You can mount volumes where data is stored by specifying https://kubernetes.io/docs/concepts/storage/persistent-volumes[PersistentVolumeClaims] for each individual role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      config:
        resources:
          storage:
            data:
              capacity: 2Gi
----

In the above example, all ZooKeeper nodes in the default group will store data (the location of the property `dataDir`) on a `2Gi` volume.

By default, in case nothing is configured in the custom resource for a certain role group, each Pod will have a `1Gi` large local volume mount for the data location.

== Resource requests

// The "nightly" version is needed because the "include" directive searches for
// files in the "stable" version by default.
// TODO: remove the "nightly" version after the next platform release (current: 22.09)
include::concepts:stackable_resource_requests.adoc[]

If no resource requests are configured explicitly, the ZooKeeper operator uses the following defaults:

[source,yaml]
----
servers:
  roleGroups:
    default:
      config:
        resources:
          memory:
            limit: '512Mi'
          cpu:
            max: '4'
            min: '500m'
          storage:
            data:
              capacity: '1Gi'
----
