= First steps

Now that the operator is installed it is time to deploy a ZooKeeper cluster and connect to it.

== Deploy ZooKeeper

The ZooKeeper cluster is deployed with a very simple resource definition. Create a file called `zookeeper.yaml`:

[source,yaml]
include::example$code/zookeeper.yaml[]

and apply it:
[source,bash]
include::example$code/getting_started.sh[tag=install-zookeeper]

The operator will create a ZooKeeper cluster with two replicas. Use kubectl to observe the status of the cluster:

[source,bash]
include::example$code/getting_started.sh[tag=watch-zookeeper-rollout]

The Operator deploys readiness probes to make sure the replicas are in quorum. Only then will the StefulSet actually be marked as `Ready`. You will see

----
partitioned roll out complete: 2 new pods have been updated...
----

The ZooKeeper is now ready.

== List nodes

ZooKeeper manages its data in a hierarchical node system. You can look at the nodes using the zkCli tool. It is included inside of Stackable ZooKeeper container, and you can invoke it using `kubectl run`:

[source,bash]
include::example$code/getting_started.sh[tag=zkcli-ls]

Among log output you will see the current list of nodes in `/`:

[source]
----
[zookeeper]
----


== Set up a ZNode

It is useful to use different nodes for different applications using ZooKeeper, and the Stackable Operator uses xref:ROOT:znodes.adoc[ZNodes] for this.
ZNodes are created with manifest files too, of the kind ZookeeperZnode. Create a file called `znode.yaml` with the following contents:

[source,yaml]
include::example$code/znode.yaml[]

And apply it:

[source,bash]
include::example$code/getting_started.sh[tag=apply-znode]

Use the same command as before to list the nodes:

[source,bash]
include::example$code/getting_started.sh[tag=zkcli-ls]

and the ZNode has appeared in the output:

----
[znode-4e0a6098-057a-42cc-926e-276ea6305e09, zookeeper]
----

Great! This step concludes the Getting started guide. You have installed the ZooKeeper Operator and it's dependencies and set up your first ZooKeeper cluster as well as your first ZNode.

== What's next

Have a look at the xref:ROOT:usage.adoc[] page to learn more about configuration options for you ZooKeeper cluster like setting up encryption or authentication. You can also have a look at the xref:ROOT:znodes.adoc[] page to learn more about ZNodes.