= Stackable Operator for Apache ZooKeeper
:description: The Stackable Operator for Apache ZooKeeper is a Kubernetes operator that can manage Apache ZooKeeper ensembles. Learn about its features, resources, dependencies and demos, and see the list of supported ZooKeeper versions.
:keywords: Stackable Operator, Hadoop, Apache ZooKeeper, Kubernetes, k8s, operator, engineer, big data, metadata, storage, cluster

The Stackable Operator for Apache ZooKeeper is a Kubernetes Operator for deploying and managing
https://zookeeper.apache.org/[Apache ZooKeeper] ensembles. Apache ZooKeeper is an open-source distributed coordination
service that facilitates synchronization, configuration management and leader election in distributed systems. ZooKeeper
is often used for these tasks in the Apache Hadoop ecosystem. Within the Stackable Platform, the Stackable Operators for
xref:hbase:index.adoc[Apache HBase], xref:hdfs:index.adoc[Apache Hadoop HDFS], xref:kafka:index.adoc[Apache Kafka] and
xref:nifi:index.adoc[Apache NiFi] depend on the ZooKeeper Operator.

== Getting started

Get started with Apache ZooKeeper and the Stackable Operator by following the xref:getting_started/index.adoc[Getting
started] guide, it will guide you through the xref:getting_started/installation.adoc[installation] process. Afterwards,
consult the xref:usage_guide/index.adoc[Usage guide] to learn more about configuring ZooKeeper for your needs. You can
also deploy a <<demos, demo>> to see an example deployment of ZooKeeper together with other data products.

== Operator model

The Operator manages two custom resources: _ZookeeperCluster_ and _ZookeeperZnode_. ZooKeeper only has a single process
that it runs, so the cluster resource only has a single corresponding xref:concepts:roles-and-role-groups.adoc[role]
called _server_.

image::zookeeper_overview.drawio.svg[A diagram depicting the Kubernetes resources created by the Stackable Operator for Apache ZooKeeper]

For every role group the Operator creates a ConfigMap and StatefulSet which can have multiple replicas (Pods). Every
role group is accessible through its own Service, and there is a Service for the whole Cluster.

The Operator creates a xref:concepts:service_discovery.adoc[service discovery ConfigMap] for the ZooKeeper instance, as
well as for each ZNode. The discovery ConfigMaps contain information on how to connect to ZooKeeper. The ZNode discovery
ConfigMap give access information for the ZNode. xref:zookeeper:znodes.adoc[learn more about ZNodes].

== Dependencies

Apache ZooKeeper and the Stackable Operator have no dependencies besides the xref:commons-operator:index.adoc[] and xref:secret-operator:index.adoc[].

== [[demos]]Demos

Apache ZooKeeper is a dependency of xref:hbase:index.adoc[Apache HBase], xref:hdfs:index.adoc[Apache Hadoop HDFS],
xref:kafka:index.adoc[Apache Kafka] and xref:nifi:index.adoc[Apache NiFi], thus any demo that uses one or more of these
components will also deploy a ZooKeeper ensemble. Here is the list of the demos that include ZooKeeper:

* xref:demos:data-lakehouse-iceberg-trino-spark.adoc[]
* xref:demos:hbase-hdfs-load-cycling-data.adoc[]
* xref:demos:jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data.adoc[]
* xref:demos:logging.adoc[]
* xref:demos:nifi-kafka-druid-earthquake-data.adoc[]
* xref:demos:nifi-kafka-druid-water-level-data.adoc[]

== Supported Versions

The Stackable Operator for Apache ZooKeeper currently supports the following versions of ZooKeeper:

WARNING: The use of 3.8.1 is strongly discouraged due to https://zookeeper.apache.org/security.html#CVE-2023-44981[Authorization bypass in SASL Quorum Peer Authentication]. Several other versions are affected but not offered by Stackable. Please take this into account when using custom images.

include::partial$supported-versions.adoc[]
