= Installation
:description: Install the Stackable operator for Apache ZooKeeper using stackablectl or Helm.

There are multiple ways to install the Stackable Operator for Apache Zookeeper.
xref:management:stackablectl:index.adoc[] is the preferred way, but Helm is also supported.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl (recommended)::
+
--
`stackablectl` is the command line tool to interact with Stackable operators and the recommended way to install
Operators. Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed `stackablectl`, use it to install the ZooKeeper Operator and its dependencies:

[source,bash]
----
include::example$getting_started/code/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/code/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`. For
example, you can use the `--cluster kind` flag to create a Kubernetes cluster with link:https://kind.sigs.k8s.io/[kind].
--

Helm::
+
--
You can also use Helm to install the operators.
Add the Stackable Helm repository:
[source,bash]
----
include::example$getting_started/code/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:
[source,bash]
----
include::example$getting_started/code/getting_started.sh[tag=helm-install-operators]
----

Helm deploys the operators in Kubernetes Deployments and applies the CRDs for the ZooKeeperCluster Stacklet.
--
====

== What's next?

Use the operator to xref:getting_started/first_steps.adoc[deploy a ZooKeeper Stacklet].
