name: Publish-Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  debian10:
    runs-on: debian10
    steps:
      - uses: actions/checkout@v2
      - uses: stackabletech/actions/publish_debian@main
        with:
          target_repo: dev
          binary_name: stackable-zookeeper-operator-server
          cargo_path: server/Cargo.toml

  centos:
    runs-on: centos${{ matrix.node }}
    strategy:
      matrix:
        node: [ 7, 8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: stackabletech/actions/publish_centos@main
        with:
          target_repo: dev
          binary_name: stackable-zookeeper-operator-server
          cargo_path: server/Cargo.toml
          centos_version: ${{ matrix.node }}