name: Publish-Artifacts

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  REPO_APT_DEV_URL: https://repo.stackable.tech/repository/deb-dev
  REPO_APT_NIGHTLY_URL: https://repo.stackable.tech/repository/deb-nightly
  REPO_RPM_DEV_URL: https://repo.stackable.tech/repository/rpm-dev
  REPO_RPM_NIGHTLY_URL: https://repo.stackable.tech/repository/rpm-nightly

jobs:
  debian10:
    runs-on: debian10
    steps:
      - uses: actions/checkout@v2
      - name: Change version if is PR
        if: ${{ github.event_name == 'pull_request' }}
        run: sed -i -e 's/^version = "\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/version = "\1-pr${{ github.event.number }}"/' server/Cargo.toml
      - name: Build
        run: ~/.cargo/bin/cargo +nightly build --verbose --release
      - name: Build apt package
        run: ~/.cargo/bin/cargo deb --manifest-path server/Cargo.toml --no-build
      - name: Publish nightly apt package
        if:  ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'  }}
        run: >-
          /usr/bin/curl
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          -H "Content-Type: multipart/form-data"
          --data-binary "@./$(find target/debian/ -name *.deb)"
          "${{ env.REPO_APT_NIGHTLY_URL }}/"
      - name: Publish dev apt package
        if: ${{ github.event_name == 'pull_request' }}
        run: >-
          /usr/bin/curl
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          -H "Content-Type: multipart/form-data"
          --data-binary "@./$(find target/debian/ -name *.deb)"
          "${{ env.REPO_APT_DEV_URL }}/"
      - name: Clean
        run: ~/.cargo/bin/cargo clean

  centos:
    runs-on: centos${{ matrix.node }}
    strategy:
      matrix:
        node: [ 7, 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Change version if is PR
        if: ${{ github.event_name == 'pull_request' }}
        run: sed -i -e 's/^version = "\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/version = "\1-pr${{ github.event.number }}"/' server/Cargo.toml
      - name: Build
        run: ~/.cargo/bin/cargo +nightly build --verbose --release
      - name: Build RPM package
        run: server/packaging/buildrpm.sh stackable-zookeeper-operator-server
      - name: Publish nightly RPM package
        if:  ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'  }}
        run: >-
          /usr/bin/curl
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          --upload-file "./$(find  target/rpm/RPMS/x86_64/ -name *.rpm)"
          "${{ env.REPO_RPM_NIGHTLY_URL }}/el${{ matrix.node }}/"
      - name: Publish dev RPM package
        if: ${{ github.event_name == 'pull_request' }}
        run: >-
          /usr/bin/curl
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          --upload-file "./$(find  target/rpm/RPMS/x86_64/ -name *.rpm)"
          "${{ env.REPO_RPM_DEV_URL }}/el${{ matrix.node }}/"
      - name: Clean
        run: ~/.cargo/bin/cargo clean
