name: Docker

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release
      - shell: bash
        env:
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: make docker
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: clean
