---
name: Nick is testing

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  test:
    name: Run Integration Test
    runs-on: ubuntu-latest
    steps:
      # TODO: Enable the scheduled runs which hard-code what profile to use
      - name: Step A
        id: a
        run: |
          echo -e "DOES_IT_WORK<<EOF\nsmoke_zookeeper-3.9.5_use-server-tls-true_use-client-auth-tls-true_openshift-false (130.85s)\nEOF" | tee -a "$GITHUB_OUTPUT"
          echo "FAILED_TESTS<<EOF\nsmoke_zookeeper-3.9.5_use-server-tls-true_use-client-auth-tls-true_openshift-false (130.85s)\nEOF" | tee -a "$GITHUB_OUTPUT"
      - name: Step B
        id: b
        env:
          DOES_IT_WORK: ${steps.a.outputs.DOES_IT_WORK}
          FAILED_TESTS: ${steps.a.outputs.FAILED_TESTS}
        run: |
          echo "output DOES_IT_WORK"
          echo "$DOES_IT_WORK"
          echo "------------"
          echo "output FAILED_TESTS"
          echo "$FAILED_TESTS"
          echo "------------"
